language: node_js
node_js:
  - "6"
install:
 - npm install -g gulp
 - npm install -g bower
 - npm install
 - bower install
script: gulp build
notifications:
 email: false
 slack: satrd-upv:T8bTpfVGmaID31yvk0F7Y20V
